vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        posts:
            uri_prefix: /uploads/images/posts/banner
            upload_destination: '%kernel.project_dir%/public/uploads/images/posts/banner'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
